support: Suppress clang warning on tst-timespec
clang warns that converting from TIME_T_MAX to double (upper_bound)
loses precision (from 9223372036854775807 to 9223372036854775808):

  tst-timespec.c:290:19: error: implicit conversion from 'time_t' (aka
  'long') to 'double' changes value from 9223372036854775807 to
  9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]
     .upper_bound = TIME_T_MAX, .lower_bound = 1, .result = 1,
                    ^~~~~~~~~~
  tst-timespec.c:48:20: note: expanded from macro 'TIME_T_MAX'
  #define TIME_T_MAX TYPE_MAXIMUM (time_t)
                     ^~~~~~~~~~~~~~~~~~~~~
  ../include/intprops.h:57:4: note: expanded from macro 'TYPE_MAXIMUM'
    ((t) (! TYPE_SIGNED (t)
  \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It does not matter for the test.

Checked on x86_64-linux-gnu.